### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by yoda333** [Griesbacher/nagflux#4]
Hello,
we get the following error when installing:

xxxx@xxxxx:/tmp# go get -u github.com/griesbacher/nagflux

 # github.com/griesbacher/nagflux/target/elasticsearch
go/src/github.com/griesbacher/nagflux/target/elasticsearch/Connector.go:38:29: error: unknown field ‘Timeout’ in ‘http.Client’
   false, false, http.Client{Timeout: time.Duration(5 * time.Second)}, 

 # github.com/griesbacher/nagflux/target/influx
go/src/github.com/griesbacher/nagflux/target/influx/Connector.go:46:24: error: unknown field ‘Timeout’ in ‘http.Client’
  client := http.Client{Timeout: timeout} 

Any solutions?

Best regards
Patrick

**Comment by Griesbacher** [comment]
Hi Patrick,

my first guess would be your go version is too old, try:
```
$ go version
```
It works with 1.5 and 1.6(current stable), I think 1.4 could also work, but I'm not sure.

Philip

**Comment by yoda333** [comment]
Hi Philip,

a new install with go 1.6 solved the problem. 
Thanks for your help.

Patrick
